export const bibleData = {
  "bibleBookList": [
      "Gen",
      "Exod",
      "Lev",
      "Num",
      "Deut",
      "Josh",
      "Judg",
      "Ruth",
      "1Sam",
      "2Sam",
      "1Kgs",
      "2Kgs",
      "1Chr",
      "2Chr",
      "Ezra",
      "Neh",
      "Esth",
      "Job",
      "Ps",
      "Prov",
      "Eccl",
      "Song",
      "Isa",
      "Jer",
      "Lam",
      "Ezek",
      "Dan",
      "Hos",
      "Joel",
      "Amos",
      "Obad",
      "Jonah",
      "Mic",
      "Nah",
      "Hab",
      "Zeph",
      "Hag",
      "Zech",
      "Mal",
      "Matt",
      "Mark",
      "Luke",
      "John",
      "Acts",
      "Rom",
      "1Cor",
      "2Cor",
      "Gal",
      "Eph",
      "Phil",
      "Col",
      "1Thess",
      "2Thess",
      "1Tim",
      "2Tim",
      "Titus",
      "Phlm",
      "Heb",
      "Jas",
      "1Pet",
      "2Pet",
      "1John",
      "2John",
      "3John",
      "Jude",
      "Rev"
  ],
  "freeType": true,
  "curPath": "English/audioBible/BBEM_complete",
  "title": "Audio Bible",
  "description": "Public domain",
  "language": "eng",
  "mediaType": "bible",
  "image": {
      "origin": "Local",
      "filename": "pics/Bible_OT.png"
  }
}

export const bibleDataNT = {
  "bibleBookList": [
      "Matt",
      "Mark",
      "Luke",
      "John",
      "Acts",
      "Rom",
      "1Cor",
      "2Cor",
      "Gal",
      "Eph",
      "Phil",
      "Col",
      "1Thess",
      "2Thess",
      "1Tim",
      "2Tim",
      "Titus",
      "Phlm",
      "Heb",
      "Jas",
      "1Pet",
      "2Pet",
      "1John",
      "2John",
      "3John",
      "Jude",
      "Rev"
  ],
  "freeType": false,
  "pathPattern": [
      1,
      "_",
      3,
      "_",
      2,
      "_ENGWEBN2DA.mp3"
  ],
  "curPath": "shared/audio/English/English_NT",
  "title": "Audiobible NT",
  "image": {
      "origin": "Local",
      "filename": "img/ser07.jpg"
  },
  "language": "eng",
  "mediaType": "bible"
}
